name: nvim configuration ci

on: push

jobs:
    build-test:
        name: Build on ${{ matrix.container }}
        runs-on: ubuntu-latest
        container: ${{ matrix.container }}
        steps:
            - id: step0
              name: checkout code
              uses: actions/checkout@v2
            - id: install-node
              run: |
                  curl -SL https://nodejs.org/dist/v14.17.3/node-v14.17.3-linux-x64.tar.xz -o node.tar.xz
                  tar xf node.tar.xz
                  sudo cp -r node*/* /usr/
            - id: install-neovim
              run: |
                  curl -LO https://github.com/neovim/neovim/releases/download/v0.5.0/nvim-linux64.tar.gz
                  tar xzf nvim-linux64.tar.gz
                  export PATH="$(pwd)/nvim-linux64/bin:$PATH"
                  nvim --version
            - id: move-to-configuration-dir
              run: |
                  mkdir ~/.config/nvim -pv
                  cp * -rf ~/.config/nvim/
                  mv ~/.config/nvim/utils/test/init.vim ~/.config/nvim/init.vim
                  ls ~/.config/nvim -la
            - id:  dependancy-install
              run: |
                  sudo apt install golang python3-pip nodejs npm ripgrep -y
                  sudo npm install -g neovim && sudo pip3 install neovim
            - id: install-neovim-plugin
              run: |
                  export PATH="$(pwd)/nvim-linux64/bin:$PATH"
                  python3 -c "print('\n'*200)" | nvim -Es -u ~/.config/nvim/init.vim +PlugInstall +qall!
